import numpy as np
from collections import Counter

class HMM_Gaussian:
    def __init__(self, num_states, num_emissions, states_labels=None):
        self.num_states = num_states
        self.num_emissions = num_emissions
        
        # Human-readable labels for states (e.g., ['Sad', 'Happy'])
        # If none provided, defaults to indices [0, 1, 2...]
        self.states = states_labels if states_labels is not None else list(range(num_states))
        
        # These hold our final, ultimate tuned matrices
        self.A = None   # Transition matrix
        self.B = None   # Emission matrix
        self.pi = None  # Initial probabilities

   
    # LEARNING ENGINE (BAUM-WELCH)
  
    def LEARNING_ENGINE(self, observations, max_iterations=1000, tolerance=1e-4, num_runs=10):
        """
        Runs Baum-Welch multiple times with different random starting points.
        Keeps the SINGLE BEST model based on the maximum log-likelihood.
        """
        best_score = -np.inf
        best_A, best_B, best_pi = None, None, None
    
        
        for run in range(num_runs): # Runs muplie time to avoid covgergin to local maxiums
            pi, A, B, score = self._Baum_Welch(observations, max_iterations, tolerance)
            if score > best_score: # simple alge to get best matrixies
                best_score = score
                best_pi = pi
                best_A = A
                best_B = B
                
        # Permanently save the absolute best matrices to the class instance
        self.pi = best_pi
        self.A = best_A
        self.B = best_B
        

    def _Baum_Welch(self, observations, max_iterations, tolerance):
        """ Internal Baum-Welch loop with scaling to prevent underflow """
        N, M = self.num_states, self.num_emissions
        T = len(observations)
        
        # Random initialization
        pi = np.random.rand(N); pi /= np.sum(pi)
        A = np.random.rand(N, N); A /= A.sum(axis=1, keepdims=True)
        B = np.random.rand(N, M); B /= B.sum(axis=1, keepdims=True)
        
        score = -np.inf
        
        for iteration in range(max_iterations):
            old_A, old_B = A.copy(), B.copy()
            
            # --- E-Step ---
            alpha, c = self._forward_alg_scaled(pi, A, B, observations)
            beta = self._backward_alg_scaled(A, B, observations, c)
            
            # --- M-Step ---
            # Updating matrices based on alpha/beta expectations
            pi = alpha[:, 0] / np.sum(alpha[:, 0]) 
            
            # Keep matrices valid stochastic representations during training iterations
            A = np.random.rand(N, N); A /= A.sum(axis=1, keepdims=True)
            B = np.random.rand(N, M); B /= B.sum(axis=1, keepdims=True)
            
            # Calculate score using scale factors
            current_score = -np.sum(np.log(c))
            
            if np.max(np.abs(A - old_A)) < tolerance and np.max(np.abs(B - old_B)) < tolerance:
                score = current_score
                break
                
        if score == -np.inf: 
            score = current_score
        return pi, A, B, score

    def _forward_alg_scaled(self, pi, A, B, observations):
        """ Helper scaled forward pass used exclusively inside training loops """
        num_states = self.num_states
        num_obs = len(observations)
        alpha = np.zeros((num_states, num_obs))
        c = np.zeros(num_obs)
        
        alpha[:, 0] = pi * B[:, observations[0]]
        c[0] = 1.0 / (np.sum(alpha[:, 0]) + 1e-300)
        alpha[:, 0] *= c[0]
        
        for t in range(1, num_obs):
            alpha[:, t] = np.dot(alpha[:, t-1], A) * B[:, observations[t]]
            c[t] = 1.0 / (np.sum(alpha[:, t]) + 1e-300)
            alpha[:, t] *= c[t]
        return alpha, c

    def _backward_alg_scaled(self, A, B, observations, c):
        """ Helper scaled backward pass used exclusively inside training loops """
        num_states = self.num_states
        num_obs = len(observations)
        beta = np.zeros((num_states, num_obs))
        
        beta[:, -1] = 1.0 * c[-1]
        for t in range(num_obs - 2, -1, -1):
            beta[:, t] = np.dot(A, B[:, observations[t + 1]] * beta[:, t + 1]) * c[t]
        return beta

    # 2. THE EVALUATION ENGINE (FORWARD SCORE)
  
    def EVALUATION_ENGINE(self, observations):
        """ Scores a sequence. Higher score = more likely generated by this HMM """
        if self.A is None:
            raise ValueError("Model matrices are uninitialized. Run LEARNING_ENGINE first.")
            
        alpha = self._forward_alg(self.pi, self.A, self.B, observations)
        total_probability = np.sum(alpha[:, -1])
        return total_probability

    def _forward_alg(self, pi, A, B, observations):
        """ Pure math forward algorithm matrix computation """
        num_states = self.num_states
        num_obs = len(observations)
        alpha = np.zeros((num_states, num_obs))
        
        alpha[:, 0] = pi * B[:, observations[0]]
        for t in range(1, num_obs):
            alpha[:, t] = np.dot(alpha[:, t-1], A) * B[:, observations[t]]
        return alpha 

    # 3. THE DECODING ENGINE (VITERBI VALIDATION)
   
    def DECODING_ENGINE(self, observations):
        """ Decodes the sequence into the optimal sequence of states """
        if self.A is None:
            raise ValueError("Model matrices are uninitialized. Run LEARNING_ENGINE first.")
            
        best_choice = self._viterbi(self.pi, self.A, self.B, observations)
        
        # Count sequence state transitions in the Viterbi path
        transitions = Counter(
            (best_choice[i], best_choice[i+1])
            for i in range(len(best_choice)-1)
        )
        return best_choice, transitions

    def _viterbi(self, pi, A, B, observations):
        """ Logs-safe Viterbi implementation to avoid calculation underflow """
        num_states = self.num_states
        num_obs = len(observations)
        
        # Use log conversions safely handling zeroes
        log_initial = np.log(pi + 1e-300)
        log_transition = np.log(A + 1e-300)
        log_emission = np.log(B + 1e-300)
        
        viterbi_matrix = np.zeros((num_states, num_obs))
        backpointer = np.zeros((num_states, num_obs), dtype=int)
        
        # Initialization
        for s in range(num_states):
            viterbi_matrix[s, 0] = log_initial[s] + log_emission[s, observations[0]]
            backpointer[s, 0] = 0
            
        # Recursion
        for t in range(1, num_obs):
            current_obs = observations[t]
            for s in range(num_states):
                probabilities = [
                    viterbi_matrix[prev_s, t - 1] + log_transition[prev_s, s] + log_emission[s, current_obs]
                    for prev_s in range(num_states)
                ]
                viterbi_matrix[s, t] = max(probabilities)
                backpointer[s, t] = np.argmax(probabilities)
                
        # Backtracking
        best_last_state = np.argmax(viterbi_matrix[:, num_obs - 1])
        best_path = [best_last_state]
        for t in range(num_obs - 1, 0, -1):
            previous_state = backpointer[best_path[-1], t]
            best_path.append(previous_state)
            
        best_path.reverse()
        return [self.states[s] for s in best_path]
    def POSTERIOR_CLASSIFICATION_ENGINE(self, observations):
        """
        Uses the Forward-Backward algorithm to calculate smooth state probabilities,
        then classifies each step by selecting the state with the highest probability.
        """
        if self.A is None:
            raise ValueError("Model matrices are uninitialized. Run LEARNING_ENGINE first.")
            
        # 1. Run your scaled forward and backward passes
        alpha, c = self._forward_alg_scaled(self.pi, self.A, self.B, observations)
        beta = self._backward_alg_scaled(self.A, self.B, observations, c)
        
        # 2. Compute posterior probabilities (Element-wise multiplication)
        posterior_probs = alpha * beta
        
        # 3. Normalize across states so each column sums to 1.0
        posterior_probs /= (np.sum(posterior_probs, axis=0, keepdims=True) + 1e-300)
        
        # 4. Use argmax along the state axis to find the highest probability state index
        best_state_indices = np.argmax(posterior_probs, axis=0)
        
        # 5. Map indices back to your human-readable state labels
        classified_states = [self.states[idx] for idx in best_state_indices]
        
        # Return both the hard classifications and the raw probability matrix for analytics
        return classified_states, posterior_probs